# the base URL
base_url = "192.168.1.9"

# example username, generated by following https://www.developers.meethue.com/documentation/getting-started
#username = "xGXxHHXdPfd4o9d398CmcmdqZ3j-0fL-li5o32xQ"

#from Tkinter import *
from phue import Bridge

'''
This example creates a slider that controls the
brightness of the first 3 lights.
'''

b = Bridge(base_url) # Enter bridge IP here.

#If running for the first time, press button on bridge and run with b.connect() uncommented
b.connect()

#b.set_light([1,2,3], 'on', True)
#lights = b.lights
l_id=0
lights = b.get_light_objects('id')
#print(lights)
# Print light names
gruppo = b.get_group(1, 'name')
stato = b.get_group(1,'on')

while True:
    if stato:
        print("Le luci di "+b.get_group(1, 'name')+": Accese")
        comando = input('Vuoi spegnerle? S/N: ')
        if comando == "S":
            b.set_group(1, 'on', False)
            stato = False
    else:
        luce = 'Spenta'
        print("Le luci di "+b.get_group(1, 'name')+": Spente")
        comando = input('Vuoi accenderle? S/N: ')
        if comando == "S":
            b.set_group(1, 'on', True)
            stato = True
